package com.wms.testdata;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * 1年分のテストデータ（SQL）を生成するスタンドアロンジェネレータ。
 *
 * <p>出力先: backend/src/main/resources/db/testdata/loadtest/
 * <p>実行: ./gradlew generateLoadTestData
 */
public final class LoadTestDataGenerator {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("yyyyMMdd");
    private static final DateTimeFormatter SQL_DATE_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    // --- データ規模パラメータ ---
    private static final int DAYS = 365;
    private static final int INBOUND_PER_DAY = 10;
    private static final int OUTBOUND_PER_DAY = 15;
    private static final int LINES_MIN = 2;
    private static final int LINES_MAX = 5;
    private static final int QTY_MIN = 3;
    private static final int QTY_MAX = 20;

    // --- マスタ参照用定数 ---
    private static final String[] SUPPLIERS =
        {"SUP001", "SUP002", "SUP003", "SUP004", "SUP005",
         "SUP006", "SUP007", "SUP008", "SUP009", "SUP010"};
    private static final String[] CUSTOMERS =
        {"CUS001", "CUS002", "CUS003", "CUS004", "CUS005",
         "CUS006", "CUS007", "CUS008", "CUS009", "CUS010"};
    private static final String[] AMBIENT_PRODUCTS = buildProductCodes("AMB", 60);
    private static final String[] REFRIGERATED_PRODUCTS = buildProductCodes("REF", 25);
    private static final String[] FROZEN_PRODUCTS = buildProductCodes("FRZ", 15);
    private static final String[] ALL_PRODUCTS = mergeArrays(AMBIENT_PRODUCTS, REFRIGERATED_PRODUCTS, FROZEN_PRODUCTS);
    private static final String[] UNIT_TYPES = {"CASE", "BALL", "PIECE"};
    private static final String[] CARRIERS = {"ヤマト運輸", "佐川急便", "日本郵便", "西濃運輸", "福山通運"};

    // ロケーション: A01/A02 の在庫エリアのみ使用（コードパターン生成）
    private static final List<String> STOCK_LOCATIONS = buildStockLocations();

    private final Random random;
    private final LocalDate startDate;
    private final Path outputDir;

    // ID カウンタ（SQL内でシーケンスに依存しないよう、INSERT時に明示的IDは使わない）
    private int inboundSeq;
    private int outboundSeq;

    public LoadTestDataGenerator(Path outputDir, long seed) {
        this.outputDir = outputDir;
        this.random = new Random(seed);
        // 開始日: 1年前の翌日
        this.startDate = LocalDate.now().minusDays(DAYS - 1);
    }

    public static void main(String[] args) throws IOException {
        Path output;
        if (args.length > 0) {
            output = Path.of(args[0]);
        } else {
            output = Path.of("src/main/resources/db/testdata/loadtest");
        }
        Files.createDirectories(output);

        System.out.println("Generating 1-year load test data to: " + output.toAbsolutePath());
        LoadTestDataGenerator gen = new LoadTestDataGenerator(output, 42L);
        gen.generate();
        System.out.println("Done.");
    }

    public void generate() throws IOException {
        generateInboundData();
        generateOutboundData();
        generateInventoryData();
        generateDailySummaryData();
    }

    // ================================================================
    // 入荷データ生成
    // ================================================================
    private void generateInboundData() throws IOException {
        Path file = outputDir.resolve("R__20_loadtest_inbound.sql");
        try (PrintWriter w = newWriter(file)) {
            w.println("-- Auto-generated: 1-year inbound test data");
            w.println("-- Generated by LoadTestDataGenerator");
            w.println();

            for (int day = 0; day < DAYS; day++) {
                LocalDate date = startDate.plusDays(day);
                String dateStr = date.format(DATE_FMT);
                String sqlDate = date.format(SQL_DATE_FMT);

                // 最後の5日分はSTORED以外のステータスも混ぜる
                boolean isFinalDays = day >= DAYS - 5;

                for (int i = 1; i <= INBOUND_PER_DAY; i++) {
                    inboundSeq++;
                    String slipNumber = String.format("INB-%s-%04d", dateStr, i);
                    String supplier = pick(SUPPLIERS);
                    String status;
                    if (isFinalDays) {
                        status = pickWeighted(new String[]{"STORED", "CONFIRMED", "PLANNED"},
                                              new int[]{60, 25, 15});
                    } else {
                        status = "STORED";
                    }

                    w.printf("INSERT INTO inbound_slips "
                            + "(slip_number, slip_type, warehouse_id, warehouse_code, warehouse_name, "
                            + "partner_id, partner_code, partner_name, planned_date, status, "
                            + "created_by, updated_by, created_at, updated_at) "
                            + "SELECT '%s', 'NORMAL', w.id, w.warehouse_code, w.warehouse_name, "
                            + "p.id, p.partner_code, p.partner_name, '%s', '%s', "
                            + "2, 2, '%s 09:00:00+09', '%s 09:00:00+09' "
                            + "FROM warehouses w, partners p "
                            + "WHERE w.warehouse_code = 'WH001' AND p.partner_code = '%s' "
                            + "AND NOT EXISTS (SELECT 1 FROM inbound_slips s WHERE s.slip_number = '%s');%n",
                            slipNumber, sqlDate, status, sqlDate, sqlDate, supplier, slipNumber);

                    // 明細
                    int lineCount = LINES_MIN + random.nextInt(LINES_MAX - LINES_MIN + 1);
                    List<String> usedProducts = new ArrayList<>();
                    for (int ln = 1; ln <= lineCount; ln++) {
                        String product = pickUnique(ALL_PRODUCTS, usedProducts);
                        usedProducts.add(product);
                        int qty = QTY_MIN + random.nextInt(QTY_MAX - QTY_MIN + 1);
                        String lineStatus;
                        if ("STORED".equals(status)) {
                            lineStatus = "STORED";
                        } else if ("CONFIRMED".equals(status)) {
                            lineStatus = "INSPECTED";
                        } else {
                            lineStatus = "PENDING";
                        }
                        String inspectedQty = "PENDING".equals(lineStatus) ? "NULL" : String.valueOf(qty);

                        w.printf("INSERT INTO inbound_slip_lines "
                                + "(inbound_slip_id, line_no, product_id, product_code, product_name, "
                                + "unit_type, planned_qty, inspected_qty, line_status, created_at, updated_at) "
                                + "SELECT s.id, %d, pr.id, pr.product_code, pr.product_name, "
                                + "'CASE', %d, %s, '%s', '%s 09:00:00+09', '%s 09:00:00+09' "
                                + "FROM inbound_slips s, products pr "
                                + "WHERE s.slip_number = '%s' AND pr.product_code = '%s' "
                                + "AND NOT EXISTS (SELECT 1 FROM inbound_slip_lines l "
                                + "WHERE l.inbound_slip_id = s.id AND l.line_no = %d);%n",
                                ln, qty, inspectedQty, lineStatus, sqlDate, sqlDate,
                                slipNumber, product, ln);
                    }
                    w.println();
                }
            }
        }
        System.out.printf("  Inbound: %d slips%n", inboundSeq);
    }

    // ================================================================
    // 出荷データ生成
    // ================================================================
    private void generateOutboundData() throws IOException {
        Path file = outputDir.resolve("R__21_loadtest_outbound.sql");
        try (PrintWriter w = newWriter(file)) {
            w.println("-- Auto-generated: 1-year outbound test data");
            w.println("-- Generated by LoadTestDataGenerator");
            w.println();

            for (int day = 0; day < DAYS; day++) {
                LocalDate date = startDate.plusDays(day);
                String dateStr = date.format(DATE_FMT);
                String sqlDate = date.format(SQL_DATE_FMT);
                boolean isFinalDays = day >= DAYS - 5;

                for (int i = 1; i <= OUTBOUND_PER_DAY; i++) {
                    outboundSeq++;
                    String slipNumber = String.format("OUT-%s-%04d", dateStr, i);
                    String customer = pick(CUSTOMERS);
                    String carrier = pick(CARRIERS);
                    String status;
                    if (isFinalDays) {
                        status = pickWeighted(
                            new String[]{"SHIPPED", "ALLOCATED", "ORDERED"},
                            new int[]{50, 30, 20});
                    } else {
                        status = "SHIPPED";
                    }

                    w.printf("INSERT INTO outbound_slips "
                            + "(slip_number, slip_type, warehouse_id, warehouse_code, warehouse_name, "
                            + "partner_id, partner_code, partner_name, planned_date, carrier, status, "
                            + "created_by, updated_by, created_at, updated_at) "
                            + "SELECT '%s', 'NORMAL', w.id, w.warehouse_code, w.warehouse_name, "
                            + "p.id, p.partner_code, p.partner_name, '%s', '%s', '%s', "
                            + "2, 2, '%s 08:00:00+09', '%s 08:00:00+09' "
                            + "FROM warehouses w, partners p "
                            + "WHERE w.warehouse_code = 'WH001' AND p.partner_code = '%s' "
                            + "AND NOT EXISTS (SELECT 1 FROM outbound_slips s WHERE s.slip_number = '%s');%n",
                            slipNumber, sqlDate, carrier, status, sqlDate, sqlDate, customer, slipNumber);

                    int lineCount = LINES_MIN + random.nextInt(LINES_MAX - LINES_MIN + 1);
                    List<String> usedProducts = new ArrayList<>();
                    for (int ln = 1; ln <= lineCount; ln++) {
                        // 出荷: 80%常温, 15%冷蔵, 5%冷凍（加重ミックス）
                        String category = pickWeighted(
                            new String[]{"AMB", "REF", "FRZ"}, new int[]{80, 15, 5});
                        String[] pool = switch (category) {
                            case "REF" -> REFRIGERATED_PRODUCTS;
                            case "FRZ" -> FROZEN_PRODUCTS;
                            default -> AMBIENT_PRODUCTS;
                        };
                        String product = pickUnique(pool, usedProducts);
                        usedProducts.add(product);
                        int qty = QTY_MIN + random.nextInt(QTY_MAX - QTY_MIN + 1);
                        String lineStatus;
                        int shippedQty;
                        if ("SHIPPED".equals(status)) {
                            lineStatus = "SHIPPED";
                            shippedQty = qty;
                        } else if ("ALLOCATED".equals(status)) {
                            lineStatus = "ALLOCATED";
                            shippedQty = 0;
                        } else {
                            lineStatus = "ORDERED";
                            shippedQty = 0;
                        }

                        w.printf("INSERT INTO outbound_slip_lines "
                                + "(outbound_slip_id, line_no, product_id, product_code, product_name, "
                                + "unit_type, ordered_qty, shipped_qty, line_status, created_at, updated_at) "
                                + "SELECT s.id, %d, pr.id, pr.product_code, pr.product_name, "
                                + "'CASE', %d, %d, '%s', '%s 08:00:00+09', '%s 08:00:00+09' "
                                + "FROM outbound_slips s, products pr "
                                + "WHERE s.slip_number = '%s' AND pr.product_code = '%s' "
                                + "AND NOT EXISTS (SELECT 1 FROM outbound_slip_lines l "
                                + "WHERE l.outbound_slip_id = s.id AND l.line_no = %d);%n",
                                ln, qty, shippedQty, lineStatus, sqlDate, sqlDate,
                                slipNumber, product, ln);
                    }
                    w.println();
                }
            }
        }
        System.out.printf("  Outbound: %d slips%n", outboundSeq);
    }

    // ================================================================
    // 在庫データ生成（現在在庫のスナップショット）
    // ================================================================
    private void generateInventoryData() throws IOException {
        Path file = outputDir.resolve("R__22_loadtest_inventory.sql");
        try (PrintWriter w = newWriter(file)) {
            w.println("-- Auto-generated: current inventory snapshot for load test");
            w.println("-- Generated by LoadTestDataGenerator");
            w.println();

            // 常温: 全60品目をロケーションに配置
            for (int i = 0; i < AMBIENT_PRODUCTS.length && i < STOCK_LOCATIONS.size(); i++) {
                String loc = STOCK_LOCATIONS.get(i);
                String product = AMBIENT_PRODUCTS[i];
                int qty = 5 + random.nextInt(16); // 5-20

                w.printf("INSERT INTO inventories "
                        + "(warehouse_id, location_id, product_id, unit_type, quantity, allocated_qty, updated_at) "
                        + "SELECT w.id, l.id, pr.id, 'CASE', %d, 0, now() "
                        + "FROM warehouses w "
                        + "JOIN locations l ON l.warehouse_id = w.id AND l.location_code = '%s' "
                        + "JOIN products pr ON pr.product_code = '%s' "
                        + "WHERE w.warehouse_code = 'WH001' "
                        + "AND NOT EXISTS (SELECT 1 FROM inventories i "
                        + "WHERE i.location_id = l.id AND i.product_id = pr.id AND i.unit_type = 'CASE');%n",
                        qty, loc, product);
            }

            // 冷蔵: B01エリア、ロット・期限付き
            String[] b01Locs = buildLocationCodes("B-01-B01", 3, 2, 5);
            for (int i = 0; i < REFRIGERATED_PRODUCTS.length && i < b01Locs.length; i++) {
                String loc = b01Locs[i];
                String product = REFRIGERATED_PRODUCTS[i];
                int qty = 3 + random.nextInt(13); // 3-15
                String lot = String.format("LOT-R%03d", i + 1);
                String expiry = LocalDate.now().plusDays(10 + random.nextInt(50)).format(SQL_DATE_FMT);

                w.printf("INSERT INTO inventories "
                        + "(warehouse_id, location_id, product_id, unit_type, lot_number, expiry_date, "
                        + "quantity, allocated_qty, updated_at) "
                        + "SELECT w.id, l.id, pr.id, 'CASE', '%s', '%s', %d, 0, now() "
                        + "FROM warehouses w "
                        + "JOIN locations l ON l.warehouse_id = w.id AND l.location_code = '%s' "
                        + "JOIN products pr ON pr.product_code = '%s' "
                        + "WHERE w.warehouse_code = 'WH001' "
                        + "AND NOT EXISTS (SELECT 1 FROM inventories i "
                        + "WHERE i.location_id = l.id AND i.product_id = pr.id "
                        + "AND i.unit_type = 'CASE' AND i.lot_number = '%s');%n",
                        lot, expiry, qty, loc, product, lot);
            }

            // 冷凍: B02エリア、ロット・期限付き
            String[] b02Locs = buildLocationCodes("B-01-B02", 2, 2, 5);
            for (int i = 0; i < FROZEN_PRODUCTS.length && i < b02Locs.length; i++) {
                String loc = b02Locs[i];
                String product = FROZEN_PRODUCTS[i];
                int qty = 3 + random.nextInt(13);
                String lot = String.format("LOT-F%03d", i + 1);
                String expiry = LocalDate.now().plusDays(60 + random.nextInt(120)).format(SQL_DATE_FMT);

                w.printf("INSERT INTO inventories "
                        + "(warehouse_id, location_id, product_id, unit_type, lot_number, expiry_date, "
                        + "quantity, allocated_qty, updated_at) "
                        + "SELECT w.id, l.id, pr.id, 'CASE', '%s', '%s', %d, 0, now() "
                        + "FROM warehouses w "
                        + "JOIN locations l ON l.warehouse_id = w.id AND l.location_code = '%s' "
                        + "JOIN products pr ON pr.product_code = '%s' "
                        + "WHERE w.warehouse_code = 'WH001' "
                        + "AND NOT EXISTS (SELECT 1 FROM inventories i "
                        + "WHERE i.location_id = l.id AND i.product_id = pr.id "
                        + "AND i.unit_type = 'CASE' AND i.lot_number = '%s');%n",
                        lot, expiry, qty, loc, product, lot);
            }
        }
        System.out.println("  Inventory: generated");
    }

    // ================================================================
    // 日次集計データ生成（365日分）
    // ================================================================
    private void generateDailySummaryData() throws IOException {
        Path file = outputDir.resolve("R__23_loadtest_daily_summary.sql");
        try (PrintWriter w = newWriter(file)) {
            w.println("-- Auto-generated: 1-year daily summary data");
            w.println("-- Generated by LoadTestDataGenerator");
            w.println();

            long runningInventory = 50000; // 初期在庫 (バラ換算)
            // 平均ケース入数 ≒ 4 (case_quantity), 平均ボール入数 ≒ 4 (ball_quantity)
            // 1ケース ≒ 4 * 4 = 16バラ (概算)
            final int piecePerCase = 16;

            for (int day = 0; day < DAYS; day++) {
                LocalDate date = startDate.plusDays(day);
                String sqlDate = date.format(SQL_DATE_FMT);

                // 入荷: 件数固定、数量にランダム変動を加える
                int inboundCount = INBOUND_PER_DAY;
                int inboundLineCount = inboundCount * (LINES_MIN + LINES_MAX) / 2;
                // 入荷は出荷より1ケースあたり数量が多い傾向（在庫が緩やかに増加）
                long inboundQty = (long) inboundLineCount
                        * (QTY_MIN + QTY_MAX + 3) / 2  // 入荷は平均値を少し高めに
                        * piecePerCase
                        + random.nextInt(500) - 200;    // ±変動

                int outboundCount = OUTBOUND_PER_DAY;
                int outboundLineCount = outboundCount * (LINES_MIN + LINES_MAX) / 2;
                long outboundQty = (long) outboundLineCount
                        * (QTY_MIN + QTY_MAX) / 2
                        * piecePerCase
                        + random.nextInt(400) - 150;

                int returnCount = random.nextInt(3); // 0-2件/日
                int returnQty = returnCount * (3 + random.nextInt(8)) * piecePerCase;

                runningInventory = runningInventory + inboundQty - outboundQty - returnQty;
                if (runningInventory < 10000) {
                    runningInventory = 10000 + random.nextInt(5000);
                }

                w.printf("INSERT INTO daily_summary_records "
                        + "(business_date, warehouse_id, warehouse_code, "
                        + "inbound_count, inbound_line_count, inbound_quantity_total, "
                        + "outbound_count, outbound_line_count, outbound_quantity_total, "
                        + "return_count, return_quantity_total, "
                        + "inventory_quantity_total, unreceived_count, unshipped_count, created_at) "
                        + "SELECT '%s', w.id, 'WH001', "
                        + "%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, now() "
                        + "FROM warehouses w WHERE w.warehouse_code = 'WH001' "
                        + "AND NOT EXISTS (SELECT 1 FROM daily_summary_records d "
                        + "WHERE d.business_date = '%s' AND d.warehouse_id = w.id);%n",
                        sqlDate,
                        inboundCount, inboundLineCount, inboundQty,
                        outboundCount, outboundLineCount, outboundQty,
                        returnCount, returnQty,
                        runningInventory,
                        random.nextInt(3), random.nextInt(5),
                        sqlDate);
            }
        }
        System.out.printf("  Daily summaries: %d records%n", DAYS);
    }

    // ================================================================
    // ユーティリティ
    // ================================================================
    private static String[] buildProductCodes(String prefix, int count) {
        String[] codes = new String[count];
        for (int i = 0; i < count; i++) {
            codes[i] = String.format("%s-%03d", prefix, i + 1);
        }
        return codes;
    }

    private static String[] mergeArrays(String[]... arrays) {
        int total = 0;
        for (String[] a : arrays) {
            total += a.length;
        }
        String[] result = new String[total];
        int pos = 0;
        for (String[] a : arrays) {
            System.arraycopy(a, 0, result, pos, a.length);
            pos += a.length;
        }
        return result;
    }

    private static List<String> buildStockLocations() {
        List<String> locs = new ArrayList<>();
        // A01: shelf 1-4, tier 1-3, pos 1-5
        for (int s = 1; s <= 4; s++) {
            for (int t = 1; t <= 3; t++) {
                for (int p = 1; p <= 5; p++) {
                    locs.add(String.format("A-01-A01-%02d-%02d-%02d", s, t, p));
                }
            }
        }
        // A02: shelf 1-4, tier 1-3, pos 1-5
        for (int s = 1; s <= 4; s++) {
            for (int t = 1; t <= 3; t++) {
                for (int p = 1; p <= 5; p++) {
                    locs.add(String.format("A-01-A02-%02d-%02d-%02d", s, t, p));
                }
            }
        }
        return locs;
    }

    private static String[] buildLocationCodes(String prefix, int shelves, int tiers, int positions) {
        List<String> locs = new ArrayList<>();
        for (int s = 1; s <= shelves; s++) {
            for (int t = 1; t <= tiers; t++) {
                for (int p = 1; p <= positions; p++) {
                    locs.add(String.format("%s-%02d-%02d-%02d", prefix, s, t, p));
                }
            }
        }
        return locs.toArray(new String[0]);
    }

    private String pick(String[] arr) {
        return arr[random.nextInt(arr.length)];
    }

    private String pickUnique(String[] arr, List<String> exclude) {
        for (int attempt = 0; attempt < 100; attempt++) {
            String val = arr[random.nextInt(arr.length)];
            if (!exclude.contains(val)) {
                return val;
            }
        }
        return arr[random.nextInt(arr.length)];
    }

    private String pickWeighted(String[] options, int[] weights) {
        int total = 0;
        for (int w : weights) {
            total += w;
        }
        int roll = random.nextInt(total);
        int cumulative = 0;
        for (int i = 0; i < options.length; i++) {
            cumulative += weights[i];
            if (roll < cumulative) {
                return options[i];
            }
        }
        return options[options.length - 1];
    }

    private static PrintWriter newWriter(Path path) throws IOException {
        return new PrintWriter(Files.newBufferedWriter(path, StandardCharsets.UTF_8));
    }
}
